# Generated by Django 3.1.5 on 2021-01-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=200)),
                ('prezime', models.CharField(max_length=200)),
                ('naziv_opga', models.CharField(max_length=200)),
                ('adresa', models.CharField(max_length=200)),
                ('telefon', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('potvrda_emaila', models.CharField(max_length=200)),
                ('lozinka', models.CharField(max_length=200)),
            ],
        ),
    ]
