# Generated by Django 3.1.5 on 2021-01-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='telefon',
            new_name='telefon2',
        ),
    ]
