# Generated by Django 3.1.5 on 2021-01-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210127_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='adresa',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='main',
            name='email',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='main',
            name='ime',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='main',
            name='ime_proizvoda',
            field=models.CharField(default='ANTE', max_length=200),
        ),
        migrations.AlterField(
            model_name='main',
            name='kategorija_proizvoda',
            field=models.CharField(default='ante', max_length=200),
        ),
        migrations.AlterField(
            model_name='main',
            name='lozinka',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='main',
            name='naziv_opga',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='main',
            name='potvrda_emaila',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='main',
            name='prezime',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='main',
            name='telefon',
            field=models.IntegerField(default='5'),
        ),
    ]
