# Generated by Django 3.1.5 on 2021-01-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210127_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='ime_proizvoda',
        ),
        migrations.RemoveField(
            model_name='main',
            name='kategorija_proizvoda',
        ),
    ]
